[PHP]
date.timezone = UTC
engine = On
short_open_tag = Off
precision = 14
output_buffering = 4096
zlib.output_compression = Off
implicit_flush = Off
serialize_precision = -1
disable_functions =
disable_classes =
realpath_cache_size = 10M
realpath_cache_ttl = 7200
zend.enable_gc = On
expose_php = Off
max_execution_time = 300
max_input_vars = 10000
max_input_time = 600
memory_limit = -1
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = On
display_startup_errors = Off
log_errors = On
log_errors_max_len = 1024
html_errors = On
variables_order = "GPCS"
request_order = "GP"
register_argc_argv = Off
post_max_size = 200M
default_charset = "UTF-8"
file_uploads = On
upload_max_filesize = 200M
max_file_uploads = 200
allow_url_fopen = On
allow_url_include = Off
default_socket_timeout = 60

[mail function]
SMTP = localhost
smtp_port = 25
mail.add_x_header = Off
sendmail_path = "/usr/bin/msmtp -t"

[Pdo_mysql]
pdo_mysql.cache_size = 2000
pdo_mysql.default_socket =

[MySQLi]
mysqli.max_persistent = -1
mysqli.allow_persistent = On
mysqli.max_links = -1
mysqli.cache_size = 2000
mysqli.default_port = 3306
mysqli.default_socket =
mysqli.reconnect = Off

[Session]
session.save_handler = files
session.save_path = /tmp
session.use_strict_mode = 0
session.use_cookies = 1
session.use_only_cookies = 1
session.name = PHPSESSID
session.auto_start = 0
session.cookie_lifetime = 0
session.cookie_path = /
session.cookie_httponly =
session.gc_probability = 0
session.gc_divisor = 1000
session.gc_maxlifetime = 1440
session.sid_length = 26
session.sid_bits_per_character = 5

[soap]
soap.wsdl_cache_enabled = 1
soap.wsdl_cache_dir = "/tmp"
soap.wsdl_cache_ttl = 86400
soap.wsdl_cache_limit = 5

[opcache]
opcache.enable = 0
opcache.enable_cli = 0
opcache.memory_consumption = 512
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 60000
opcache.validate_timestamps = 0
opcache.consistency_checks = 0
